name = "planning-beyond-digits"
compatibility_date = "2024-09-28"

[env.production]
name = "planning-beyond-digits"

[[env.production.routes]]
pattern = "planning-beyond-digits.pages.dev"
zone_name = "pages.dev"
